const express =  require("express")
const { UserController } = require("../../controllers")
const {UserMiddlewares,AuthMiddlewares} = require("../../middlewares")
const {upload} = require("../../utils/common/fileUpload")
const router = express.Router()
router.use(express.json())
router.post("/register",UserMiddlewares.validateRegisterUser,UserController.createUser)
router.post("/login",UserMiddlewares.validateCreateRequest,UserController.loginUser)
router.post("/logout",UserController.logout)
router.get("/info",AuthMiddlewares.protect,UserController.userInfo)
router.patch("/updateprofile",AuthMiddlewares.protect,UserController.updateUserProfile)
router.patch("/updateprofilepicture",AuthMiddlewares.protect,upload.single("profilePicture"),UserController.updateUserProfilePicture)
router.post("/forgotPassword",UserController.forgotPassword)
router.patch("/changepassword",AuthMiddlewares.protect,UserMiddlewares.validatechangePassword,UserController.changePassword)
router.patch("/resetPassword/:resetToken",UserMiddlewares.validateResetPassword,UserController.resetPassword)
router.patch("/removeFriend/:friendId",AuthMiddlewares.protect,UserController.removeFriend)
module.exports=router;