module.exports = {
  UserController: require("./user-controller"),
  BillController: require("./bill-controller"),
  BudgetController: require("./budget-controller"),
  CommentController: require("./comment-controller"),
  DebtController: require("./debt-controller"),
  DownvoteController: require("./downvote-controller"),
  PaymentController: require("./payment-controller"),
  PostController: require("./post-controller"),
  ReplyController: require("./reply-controller"),
  SplitController: require("./split-controller"),
  TargetController: require("./target-controller"),
  TransactionController: require("./transaction-controller"),
  UpvoteController: require("./upvote-controller"),
};
